### ISSUE TITLE
Schach zug der Kleinen/großen Rochade nicht möglich

### ISSUE THREAD

**Issue by Popaulol** [T2brozz/Chess#7]
Man Kann den Relativ unwichtigen Schachzug der Rochade nicht ausführen bei dem König und Turm sich zusammenbewegen und Plätze Tauchen. Englisches Wikipedia: https://en.wikipedia.org/wiki/Castling oder https://de.wikipedia.org/wiki/Rochade

**Comment by Popaulol** [comment]
Hab gesehen dass es schon ein Issue damit gibt

**Comment by T2brozz** [comment]
Alles Gut. Danke für die Links, ich werde mich demnächst damit mal beschäftigen
